### ISSUE TITLE
Multiplicative identity in vector space?

### ISSUE THREAD

**Issue by sigs** [peeterjoot/GAelectrodynamics#2]
Surely the multiplicative identity belongs to the field and not the vector space (since multiplication between vectors isn't yet defined).

So:
https://github.com/peeterjoot/GAelectrodynamics/blob/5d779f9b855a1787e9c98659ed5cab5603afd054/prereq_vectorspace.tex#L33
Should probably be
```
There exists a multiplicative identity \( 1 \in \bbR \) & \( 1 \Bx = \Bx \) \\ \hline
```
Or simply
```
\( 1 \in \bbR \) is the multiplicative identity & \( 1 \Bx = \Bx \) \\ \hline
```
since we assume reals are already known.

**Comment by peeterjoot** [comment]
Fixed in e495adad263f1ddbd10089aeb4c121cb65580de8.

I've removed any mention of whether 1 is a member of the field or the vector space.  This is consistent with what is done in the linear algebra books that I own.
