### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by EvanMisshula** [peeterjoot/GAelectrodynamics#3]
After following instructions to build from latex source:

make: *** No rule to make target '/home/evan/physicsplay/mathematica/METADATA', needed by 'mathematica.tex'.  Stop.

Can you give me any hint to fix.  If I find something in the next few days I will close the issue myself.

Thank you!

**Comment by peeterjoot** [comment]
There's a couple different sets of instructions.  Can you cut and paste exactly which ones you tried to follow?

**Comment by peeterjoot** [comment]
This appears to work (slightly modified version of the instructions in version_bash.tex)

```
git clone git@github.com:peeterjoot/latex-notes-compilations.git peeterjoot
cd peeterjoot

submods="figures/GAelectrodynamics figures/gabook mathematica GAelectrodynamics gapauli latex frequencydomain"
for i in $submods ; do
   git submodule update --init $i
   (cd $i && git checkout master)
done

export PATH=`pwd`/latex/bin:$PATH

cd GAelectrodynamics
cp ../latex/scrpage2.sty . # required w/ recent mactex, perhaps not for you
make mmacells.sty parameters.sty all
```

**Comment by peeterjoot** [comment]
Fixed with:

```
commit 6900cfb40774b73d115174315825c2b68ee0f557 (HEAD -> master, origin/master, origin/HEAD)
Author: Peeter Joot <peeter.joot@lzlabs.com>
Date:   Tue Apr 26 10:21:24 2022 -0400

    version_bash.tex
       test drove build instructions (slight fix required.)
```

I'll see if I have a clean machine around that I can try on to see if there are any other dependencies.
