### ISSUE TITLE
damping

### ISSUE THREAD

**Issue by prlw1** [peeterjoot/GAelectrodynamics#4]
Consulting your excellent book (V0.1.16-19 562c2ff) after having excercised the Dad-forcing-function on a rather old swing, I think there should be a damping constant k in equations 2.127 and 2.129 ?

(daughter calls these the "Schaukeln equations")

**Comment by peeterjoot** [comment]
Thank you very much!

If you would like credit in the preface, please let me know your name (can email that directly if you don't want that here.).  For now, I've credited you as 'prlw1 (on github.)'
