### ISSUE TITLE
Is the unit weber not "Wb"?

### ISSUE THREAD

**Issue by WiredMic** [peeterjoot/GAelectrodynamics#5]
https://github.com/peeterjoot/GAelectrodynamics/blob/4a0316ed7c2be7b7c22a4a379749ee3f5c97e1f0/freespace.tex#L55

From what I can [find](https://www.britannica.com/science/weber), the abbreviation of `weber` is `Wb` and not `W`. This also make it clearer that you are not talking about watts.

I may be wrong. I am still trying to learn

**Comment by peeterjoot** [comment]
You are right, as verified in the SI document:

https://www.bipm.org/en/publications/si-brochure

I will fix it.

**Comment by peeterjoot** [comment]
ps.  Will add you to the thanks list in the preface.  Do you have a name that you'd like used, or just "WiredMic"?
